server:
  port: 5015

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: hiru
    password: test@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
